### ISSUE TITLE
mocha vs uninitialized constant Mocha::Integration::TestUnit::AssertionCounter

### ISSUE THREAD

**Issue by grosser** [freerange/mocha#110]
I propose adding this hack :)

```
Mocha::Integration::TestUnit::AssertionCounter = Mocha::Integration::AssertionCounter
class Test::Unit::TestResult
  def assert(x)
  end
end
```

**Comment by rohanthewiz** [comment]
This saved our butts. We are stuck on Rails 2.3 as upgrading Rails would be formidable - our app is humongous! Believe it or not though, we were able to upgrade our ruby from 1.9.3 to 2.2.2 using this and a few other monkey patches. Thanks!

**Comment by grosser** [comment]
I bet ours is bigger, we sill pulled it off ;)
FYI
 - https://github.com/grosser/rails2_asset_pipeline
 - https://developer.zendesk.com/blog/updating-rails-versions-while-keeping-the-business-running
 - you have to go straight to rails 3.2 and will take ~50% performance hit ... so yeah good times ;)
