### ISSUE TITLE
Redefine a class constant

### ISSUE THREAD

**Issue by fguillen** [freerange/mocha#13]
I would like to mock a class constant but it does not work:

```
require 'test/unit'
require 'mocha'

class A
  MY_CONST = 'a'
end

class MyTest < Test::Unit::TestCase
  def test_should_returns_b
    assert_equal( 'a', A::MY_CONST )
    A.stubs( :MY_CONST ).returns( 'b' )
    assert_equal( 'b', A::MY_CONST )
  end
end
```

Is there any way to do something like this?

Thanks.

f.

**Comment by mariusbutuc** [comment]
Still comes up high in google searches so FWIW here are my ¢2: wrap the constant in a class method
```ruby
class Fetcher
  DATA_FILE = 'tmp/real_data.csv'.freeze
  # …
  def self.data_file
    DATA_FILE
  end
end
```
that we can later stub in the test:
```ruby
class FetcherTest < ActiveSupport::TestCase
  def setup
    Fetcher.stubs(:data_file).returns('test/fixtures/files/test_data.csv')
  end
  # …
end
```

**Comment by grosser** [comment]
```
  def stub_const(const, value)
    old = A.const_get(const)
    A.send(:remove_const, const)
    A.const_set(const, value)
    yield
  ensure
    A.send(:remove_const, const)
    A.const_set(const, old)
  end
```

**Comment by fwuensche** [comment]
Just a small improvement on top of @grosser's method:

```ruby
  def stub_constant(klass, const, value)
    old = klass.const_get(const)
    klass.send(:remove_const, const)
    klass.const_set(const, value)
    yield
  ensure
    klass.send(:remove_const, const)
    klass.const_set(const, old)
  end
```

So you can now stub constants from different classes: 

```ruby
  it 'actually sends notification messages on slack' do
    stub_constant(Notification, :SLACK_CHANNEL, '#test') do
      stub_constant(User, :ADMIN_SLACK_ID, '78UIMF1') do
        Notification.master_alert
      end
    end
  end
```

**Comment by Ajwah** [comment]
@floehopper 
> Can you give us a more real-world example? It's always easier to talk about something more concrete

You are right that it is a code smell that constants are to be redefined during tests. A real-world example where this still is used is where you start of writing the application thinking something to be a constant, and 50k loc later you see that assumption was not well thought out. When dealing with legacy applications, it can be rather painful to refactor such constants. 

As such, it would be valuable to introduce this, even it be under the token of: 
['i_suck_and_need_to_stub_a_constant!' ](https://dominicwong617.github.io/ruby/2015/01/13/i-suck-and-my-tests-are-order-dependent/)
