### ISSUE TITLE
Better handling for mock names that are not Strings

### ISSUE THREAD

**Issue by floehopper** [freerange/mocha#176]
See https://github.com/freerange/mocha/issues/174.

The documentation does say that the name should be a String [1], but I think this could be made clearer; or the symbol should be rejected; or the method should accept a symbol name.

[1] http://gofreerange.com/mocha/docs/Mocha/API.html#mock-instance_method

**Comment by nitishr** [comment]
Is this resolved with #377 ?

**Comment by floehopper** [comment]
> Is this resolved with #377 ?

Yes, although this did make me wonder whether we should deprecate the old accidental behaviour described in #347 before we release the changes in #377.

Either way, I'm happy to close this issue. Thanks for the prompt to do so.
