### ISSUE TITLE
Return value from Mocha::Mock#stubs & #expects should not be Hash

### ISSUE THREAD

**Issue by floehopper** [freerange/mocha#211]
In #209 @tmertens suggests that the return value should be the mock object itself.

In any case, the documentation suggests the return value is an `Expectation`, which is incorrect.

We could consider returning any of the following:
- The mock object
- The last expectation
- The `ExpectationList`
- `nil`

Need to think about which is the least confusing/unexpected.

**Comment by nitishr** [comment]
I don't think this is true anymore. See [counterexample](https://github.com/freerange/mocha/blob/master/test/unit/mock_test.rb#L13).

**Comment by floehopper** [comment]
> I don't think this is true anymore. See [counterexample](https://github.com/freerange/mocha/blob/master/test/unit/mock_test.rb#L13).

I think this link is out-of-date. I assume it was pointing at the following line:

https://github.com/freerange/mocha/blob/b7a7d23321e409c9ad77229f80033a55eb0d8a90/test/unit/mock_test.rb#L22

**Comment by floehopper** [comment]
This was fixed in b6b637db7326e92299d4622f9e6847f3c7d58d91 in #525 which addressed #524. The change was released in v1.14.0. Closing.
