### ISSUE TITLE
Returns with block and inspecting arguments?

### ISSUE THREAD

**Issue by hakunin** [freerange/mocha#213]
Hi, I am moving away from now not maintained gem `rr` and wanted to ask if there is any plan to be able to do this (pseudocode):

```
args = []
SomeClass.any_instance.stub(:perform) do  |a, b, c|
  args << [a, b, c]; nil
end

assert_equal "what I expected to get", args
```

I see that the current code could be extended to do that, would there be interest for a pull request?

**Comment by floehopper** [comment]
@hakunin: I'm busy with work at the moment, but I'll reply as soon as I can.

**Comment by floehopper** [comment]
@hakunin: I'm sorry not to have replied for ages.

Can you explain a bit more about exactly what you're trying to achieve? You can achieve something pretty similar to what it looks like you want as follows:

```ruby
class FooTest < Minitest::Test
  class Foo
    def self.bar(*args)
    end
  end

  def test_foo
    Foo.expects(:bar).with(1, 2, 3)
    Foo.bar(2, 3, 4)
  end
end
```

This gives the following output:

```
$ ruby -Itest foo.rb
Run options: --seed 62486

# Running:

F

Finished in 0.002787s, 358.8088 runs/s, 0.0000 assertions/s.

  1) Failure:
FooTest#test_foo [foo.rb:13]:
unexpected invocation: FooTest::Foo.bar(2, 3, 4)
unsatisfied expectations:
- expected exactly once, not yet invoked: FooTest::Foo.bar(1, 2, 3)


1 runs, 0 assertions, 1 failures, 0 errors, 0 skips
```

i.e. this output shows what arguments were expected and what arguments were actually received.

**Comment by hakunin** [comment]
Hi, thanks for the reply. My goals are:

1) sometimes I just need to run code instead of the method
2) one use-case is to collect the arguments, the method is called multiple times though

**Comment by Hubro** [comment]
It would be useful to be able to stun out a method and replace it with another method. Currently I am doing this to stub out methods that go over the network:

def setup
  data = get_test_data("addresses")

  @subject = ClassToBeTested.new

  @subject.define_singleton_method(:a_search_address) { |address|
    data[:a][address] or fail "Unexpected address: #{address}"
  }

  @subject.define_singleton_method(:b_search_address) { |address|
    data[:b][address] or fail "Unexpected address: #{address}"
  }

  @subject.define_singleton_method(:c_search_address) { |address|
    data[:c][address] or fail "Unexpected address: #{address}"
  }
end

I think this would be cleaner, especially when stubbing out class methods, and not instance methods like in this case:

def setup
  data = get_test_data("addresses")

  ClassToBeTested.any_instance.stub(:a_search_address) { |address|
    data[:a][address] or fail "Unexpected address: #{address}"
  }

  ClassToBeTested.any_instance.stub(:b_search_address) { |address|
    data[:b][address] or fail "Unexpected address: #{address}"
  }

  ClassToBeTested.any_instance.stub(:c_search_address) { |address|
    data[:c][address] or fail "Unexpected address: #{address}"
  }

  @subject = ClassToBeTested.new
end

**Comment by floehopper** [comment]
Closing in favour of #224.
