### ISSUE TITLE
NoMethodError: undefined method `any_instance' for ClassName

### ISSUE THREAD

**Issue by mcshakes** [freerange/mocha#218]
Hey,

So when I run `rake test` on this file:

```ruby
require_relative '../test_helper'

class UserProfileTest < ActionDispatch::IntegrationTest
  include Capybara::DSL
  attr_reader :user

  def setup
    @user = User.create(user_name: 'kip', password: 'pass')
  end

  test "registered user can view their profile" do
    ApplicationController.any_instance.stubs(:current_user).returns(user)
    visit user_path(user)
    within("#banner") do
      assert page.has_content?("kip's profile")
    end
  end
end
```

I get this error message:

```
1) Error:
UserProfileTest#test_registered_user_can_view_their_profile:
NoMethodError: undefined method any_instance' for ApplicationController:Class test/integration/user_profile_test.rb:12:inblock in class:UserProfileTest'
```

Am I doing something wrong as far as loading up mocha within my Gemfile? I've loaded it like this:

```ruby
group :development, :test do
  gem 'byebug'

  gem 'web-console', '~> 2.0'
  gem 'capybara'
  gem 'launchy'
  gem 'rspec-rails'
  gem 'mocha'
end
```

**Comment by floehopper** [comment]
@mcshakes: I hope you don't mind, but I've re-formatted your submission to make it easier to read.

**Comment by floehopper** [comment]
@mcshakes: Did you follow the instructions here? - https://github.com/freerange/mocha#rails. In particular did you add this line to your `test_helper.rb`?

```ruby
require 'mocha/mini_test'
```

**Comment by mcshakes** [comment]
No problem at all. I was wondering how to format it properly (this was the first issue I opened). I was going off a tutorial/code-along we had in class today, and didn't have that. I'll try it.
What I did do to get it to work was add:
require "mocha/setup"

in the test_helper.rb

Does that not do anything?

**Comment by mcshakes** [comment]
Ok, it also works with:
require 'mocha/mini_test'

I'll use that from now on. The test_helper.rb within the tutorial didn't have either requirements

**Comment by floehopper** [comment]
I _think_ `require 'mocha/setup'` should also work - did it not work? The difference is that it will try to work out whether you are using Test::Unit or MiniTest and sets Mocha up accordingly; whereas using the recommended `require 'mocha/mini_test'` *explicitly* tells Mocha to set itself up for use with MiniTest.

**Comment by mcshakes** [comment]
Yep, they both work. I've made sure to use the require 'mocha/mini_test'. Right now, I'm also trying to figure out why the method is working in another program without either of,
require 'mocha/mini_test'
or
require 'mocha/setup'

in test_helper.rb
Anyways, thanks so much for the help!

**Comment by floehopper** [comment]
The recommendation to use `require 'mocha/mini_test'` is a relatively recent one - it was [introduced in v1.0.0](http://gofreerange.com/mocha/docs/file.RELEASE.html#1_0_0). Perhaps the tutorial pre-dates this change.

I'm going to close this issue now on the assumption that everything is working as expected. Please re-open it if not.

**Comment by shawndeprey** [comment]
@floehopper recommendation is still the correct fix here if you're hitting this error.

**Comment by floehopper** [comment]
@shawndeprey I'm not sure what you mean. Have you followed [these instructions](https://github.com/freerange/mocha#rails)? They should be up-to-date.
