### ISSUE TITLE
Verification of stubbing not existing methods

### ISSUE THREAD

**Issue by bjarosze** [freerange/mocha#235]
I have a question regarding stubs.

Lets say I have two classes: A and B:

```ruby
class A
  def method_a(b)
    b.method_b
  end
end

class B
  def method_b
     # some logic with lot of dependencies
  end
end
```

I want to test A.method_a, but class B has a lot of dependencies used in method_b, so I decided to stub it.
```ruby
  b = B.new
  b.stubs(:method_b => 'test')
```
My test is ok, but when I change name of method_b to something else, then test will still pass, but method_a will stop to work because it will have reference to not existing method. So I get positive false.

My question is: would it be good solution to implement in mocha (maybe as an option) some verification if stubbed method is really implemented in original object and throw exception if not?

**Comment by floehopper** [comment]
This option already exists, although I've just realised it isn't well documented. You need to configure Mocha like this: `Mocha::Configuration.prevent(:stubbing_non_existent_method)`.

* [Mocha::Configuration docs](http://gofreerange.com/mocha/docs/Mocha/Configuration.html)
* [Mocha Configuration blog post](http://jamesmead.org/blog/2009-02-09-mocha-configuration)

**Comment by floehopper** [comment]
I've added a new issue to improve the docs for Mocha config - #236.

I'm going to close this issue. Please re-open it if this doesn't solve your problem.
