### ISSUE TITLE
/Users/palak.agarwal/ra-payable/.bundle/ruby/2.1.0/gems/activesupport-3.1.3/lib/active_support/testing/setup_and_teardown.rb:103:in `retrieve_mocha_counter': uninitialized constant Mocha::Integration::TestUnit (NameError)

### ISSUE THREAD

**Issue by palakA03** [freerange/mocha#242]
Please let me know why local testing environment is failing with this error.

**Comment by floehopper** [comment]
Looking at the stack trace, it look as if you are using Ruby v2.1.0 and Rails (?) v3.1.3. Is that correct?

I'm guessing that when you say "local testing environment", you mean that this exception is happening when you run the tests in a Rails app. Is that correct?

I've tried to reproduce your problem by creating [this vanilla Rails app][1] with the appropriate version of Ruby & Rails, but I do not see the same problem.

* Did you follow [these instructions on how to set Mocha up in Rails][2]?
* Are you using standard Rails tests?
* Have you got any testing related gems installed? e.g. MiniTest, RSpec
* What version of Mocha are you using?

Can you see anything different about what I've done in the vanilla Rails app? i.e. can you tell me how to reproduce your problem in that app? The following files/lines are of particular relevance:

* https://github.com/mocha-rb/rails-v3.1.3-with-mocha/blob/master/Gemfile#L36
* https://github.com/mocha-rb/rails-v3.1.3-with-mocha/blob/master/test/test_helper.rb#L5

[1]: https://github.com/mocha-rb/rails-v3.1.3-with-mocha
[2]: https://github.com/freerange/mocha#rails

**Comment by floehopper** [comment]
@palakA03: Since I haven't heard from you in over 2 weeks, I'm closing this issue. Please re-open it if you have further information for me.
