### ISSUE TITLE
Consider updating Travis CI build matrix

### ISSUE THREAD

**Issue by floehopper** [freerange/mocha#246]
The build currently mostly tests against Ruby v1.8.7 & v1.9.3 with various combinations of other gems. It might make sense to test these combinations against other more common/recent versions of Ruby.

~~Also it only tests against Ruby v1.8.7, v1.9.3, v2.0.0, v2.1, v2.2. It would be nice to test against v2.3 as well.~~

**Comment by chrisroos** [comment]
I've added Ruby 2.3 to the Travis config in PR #263.

**Comment by floehopper** [comment]
I've updated the description to take account of #263.

**Comment by floehopper** [comment]
This issue is ancient and the matrix has been updated multiple times in the meantime and we've switched from Travis CI to CircleCI. Closing.
