### ISSUE TITLE
Prevent mocking/stubbing specific classes

### ISSUE THREAD

**Issue by JustSilverman** [freerange/mocha#249]
Is it possible to disable mocha or prevent mocking/stubbing methods on instances of specific classes?

Thanks

**Comment by chrisroos** [comment]
Hi @JustSilverman. Can you expand on what you're trying to do, please?

**Comment by chrisroos** [comment]
I'm going to close this issue given I've not heard anything back.

@JustSilverman: Feel free to reopen with some additional information if you're still interested in this issue.
