### ISSUE TITLE
Setting expectation on private method inherited from Kernel not working

### ISSUE THREAD

**Issue by chrisroos** [freerange/mocha#260]
This has been created based on [@grosser's comment][1] in PR #244.

You can replicate the problem by creating the following acceptance test in test/acceptance/setting_expectation_on_private_method_test.rb:

```ruby
require File.expand_path('../acceptance_test_helper', __FILE__)
require 'mocha/setup'

class SettingExpectationOnPrivateMethodTest < Mocha::TestCase
  include AcceptanceTest

  def setup
    setup_acceptance_test
  end

  def teardown
    teardown_acceptance_test
  end

  def test_setting_expectation_on_private_method_inherited_from_kernel
    instance = Class.new.new

    instance.expects(:warn)
    instance.warn
  end
end
```

NOTE. This is slightly different from the code in @grosser's comment (the class under test doesn't include a `method_missing`) but I _think_ it illustrates the same problem.

Running the test against master (2c6420966b7533d373cc7ac40d87fbc9bbb430c0) results in the following failure:

```bash
$ bundle exec ruby test/acceptance/setting_expectation_on_private_method_test.rb 
Run options: --seed 30417

# Running:

E

Finished in 0.001600s, 625.0000 runs/s, 0.0000 assertions/s.

  1) Error:
SettingExpectationOnPrivateMethodTest#test_setting_expectation_on_private_method_inherited_from_kernel:
NoMethodError: private method `warn' called for #<#<Class:0x007fc6e6c43178>:0x007fc6e6c43128 @mocha=nil>
    test/acceptance/setting_expectation_on_private_method_test.rb:19:in `test_setting_expectation_on_private_method_inherited_from_kernel'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

Running the test against the v1.1.0 tag results in a pass:

```bash
$ bundle exec ruby test/acceptance/setting_expectation_on_private_method_test.rb 
Run options: --seed 59809

# Running tests:

.

Finished tests in 0.002051s, 487.5670 tests/s, 487.5670 assertions/s.

1 tests, 1 assertions, 0 failures, 0 errors, 0 skips
```

[1]: https://github.com/freerange/mocha/pull/244#issuecomment-242502851

**Comment by chrisroos** [comment]
I think the change in behaviour was introduced in e87c03b068efc48267fbcd5a295514077c52b901.

Running the test against `e87c03b068efc48267fbcd5a295514077c52b901`:

```bash
$ git co e87c03b068efc48267fbcd5a295514077c52b901

$ bundle exec ruby test/acceptance/setting_expectation_on_private_method_test.rb 
Run options: --seed 8006

# Running tests:

E

Finished tests in 0.002969s, 336.8137 tests/s, 0.0000 assertions/s.

  1) Error:
SettingExpectationOnPrivateMethodTest#test_setting_expectation_on_private_method_inherited_from_kernel:
NoMethodError: private method `warn' called for #<#<Class:0x007fac48952850>:0x007fac48952800>
    test/acceptance/setting_expectation_on_private_method_test.rb:19:in `test_setting_expectation_on_private_method_inherited_from_kernel'
    <snipped>

1 tests, 0 assertions, 0 failures, 1 errors, 0 skips
```

Running the test against `e87c03b068efc48267fbcd5a295514077c52b901~`:

```bash
$ git co e87c03b068efc48267fbcd5a295514077c52b901~

$ bundle exec ruby test/acceptance/setting_expectation_on_private_method_test.rb 
Run options: --seed 35086

# Running tests:

.

Finished tests in 0.001977s, 505.8169 tests/s, 505.8169 assertions/s.

1 tests, 1 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by grosser** [comment]
I think `instance.warn` should fail since it is calling a private method ... but not that big of a deal ...

I'd recommend to also add a test for the method_missing + private method madness just in case ;)

**Comment by chrisroos** [comment]
Thanks @grosser. I've created a branch with the failing tests in PR #261. I'll take a look at it soon(ish).

**Comment by chrisroos** [comment]
Commit 5f768de62a6b6fb2c1c275b5830bc6471722cce4 adds tests to help us avoid breaking this new behaviour in future.

**Comment by chrisroos** [comment]
I've added the 'wont-fix' label and am going to close this issue.

@grosser: Feel free to re-open this if you disagree with our decision.

**Comment by grosser** [comment]
that makes sense ... stubbing method_missing should do the trick ... 
ideally the stub would work too since eventually `warn` got called, but no big deal :)

**Comment by chrisroos** [comment]
What do you mean by, "ideally the stub would work too since eventually warn got called", @grosser? I wonder if I've misunderstood something about your original code.

**Comment by grosser** [comment]
ah no ... I got that wrong ... warn never got called ... so the stub should have failed :)
