### ISSUE TITLE
Hanging issue with mocha with Ruby 2.3.1 (hide_original_method)

### ISSUE THREAD

**Issue by petems** [freerange/mocha#272]
This is a multi-part issue with various moving pieces, but mocha seems to be the issue.

So, we have some code that does testing of Facter facts and as part of that testing, we mock out values:

```ruby
require 'spec_helper'

describe Facter::Util::Fact do
  before { Facter.clear }

  describe 'nginx_version' do

    before do
      Facter::Util::Resolution.stubs(:exec)
    end

    context 'neither nginx or openresty in path' do
      before do
        Facter::Util::Resolution.stubs(:which).with('nginx').returns(false)
        Facter::Util::Resolution.stubs(:which).with('openresty').returns(false)
      end
      it { expect(Facter.fact(:nginx_version).value).to eq(nil) }
    end
    context 'nginx in path' do
      context 'with current version output format' do
        before do
          Facter::Util::Resolution.stubs(:which).with('nginx').returns(true)
          Facter::Util::Resolution.stubs(:exec).with('nginx -v 2>&1').returns('nginx version: nginx/1.8.1')
        end
        it { expect(Facter.fact(:nginx_version).value).to eq('1.8.1') }
      end
      context 'with old version output format' do
        before do
          Facter::Util::Resolution.stubs(:which).with('nginx').returns(true)
          Facter::Util::Resolution.stubs(:exec).with('nginx -v 2>&1').returns('nginx: nginx version: nginx/0.7.0')
        end
        it { expect(Facter.fact(:nginx_version).value).to eq('0.7.0') }
      end
    end
    context 'openresty in path' do
      context 'with current version output format' do
        before do
          Facter::Util::Resolution.stubs(:which).with('nginx').returns(false)
          Facter::Util::Resolution.stubs(:which).with('openresty').returns(true)
          Facter::Util::Resolution.stubs(:exec).with('openresty -v 2>&1').returns('nginx version: openresty/1.11.2.1')
        end
        it { expect(Facter.fact(:nginx_version).value).to eq('1.11.2.1') }
      end
      context 'with old version output format' do # rubocop:disable RSpec/EmptyExampleGroup
      # Openresty never used the old format as far as I can find, no point testing
      end
    end
  end
end
```

However, tests started hanging on 2.3.1 Ruby with the latest mocha release:
https://travis-ci.org/voxpupuli/puppet-nginx/builds/166701701

With a bit of debugging with https://github.com/jvns/ruby-stacktrace, the following was coming up in the stacktrace:

```
 self | tot  | method
 100.0% | 33.3% | hide_original_method : /root/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mocha-1.2.0/lib/mocha/class_method.rb
```

We then pinned Mocha back to `1.1.0` and it would work as normal.

So something from the change made in https://github.com/freerange/mocha/pull/262 hangs on Ruby 2.3.1 for us. I'll see if I can recreate in a minitest or something.

Any help appreciated! 👍

**Comment by floehopper** [comment]
The most significant changes between Mocha v1.1.0 & v1.2.0 are the first 5 lines of the [release notes](https://github.com/freerange/mocha/blob/master/RELEASE.md#120). Essentially there are 3 things that have changed:

1. In recent versions of Ruby, we now define the stub method using a prepended module which "hides" the original implementation. This module is then removed at the end of the test, revealing the original implementation.
2. We've fixed some incorrect behaviour which meant that the visibility of the stub method was not being set to the same as the stubbed method i.e. if you are stubbing a private method, you would expect the stub method to also be private.
3. Make the `stubbing_non_existent_method` configuration option work with "any instance" stubs.

My guess is that your problem is related to points 1 or 2.

You mention #262. Have you specifically narrowed it down to that PR? Or just the change of version from 1.1 -> 1.2?

I haven't got loads of time to look at this at the moment, so could you try and come up with a simple test case which I can use to reproduce the problem? If so, I'll do my best to look into it as soon as I can.

**Comment by petems** [comment]
So yep, #262 is innocent, I reverted it on a branch and it still didn't work.

It looks like the changes in 43d56671944bd0c61e93eee89f67eb2d1736574e are the culprit.

78d930a7e724319904a87abf24d85033b024cdfd working
a4ba95bb04995721e3f46423a86ffbf0e4a9f079 working
43d56671944bd0c61e93eee89f67eb2d1736574e not working

**Comment by floehopper** [comment]
I'm guessing the fact that your tests are "hanging" might be because a call to something like `Kernel#exec` is actually trying to run the shell command i.e. the stub for it is not working. Does that sound right? If so, are you able to verify that is what is happening?

**Comment by petems** [comment]
Under the hood Facter would running a command on the system yeah.

How can I verify if the stub isn't working? Is there a way to list all methods called that aren't being stubbed?

And how come it only happens on 2.3.1?

**Comment by floehopper** [comment]
> So yep, #262 is innocent, I reverted it on a branch and it still didn't work.
>
> It looks like the changes in 43d56671944bd0c61e93eee89f67eb2d1736574e are the culprit.
>
> 78d930a7e724319904a87abf24d85033b024cdfd working
> a4ba95bb04995721e3f46423a86ffbf0e4a9f079 working
> 43d56671944bd0c61e93eee89f67eb2d1736574e not working

OK - that's really useful to know. Thanks.

> Under the hood Facter would running a command on the system yeah. How can I verify if the stub isn't working?

I don't know anything about Facter. Can you have it run a command which has a detectable side-effect? e.g. if you can see the stdout from those commands, you could have it run something like `echo 'hello'`; or if you can see the filesystem on which it operates, you could have it run something like `touch /tmp/foo.txt`.

> Is there a way to list all methods called that aren't being stubbed?

No, I don't think so. If it really isn't being called, the code execution path will not pass through Mocha.

> And how come it only happens on 2.3.1?

Good question. Just to double-check, does the Facter project build OK in Ruby v2.3.1 without your changes?

**Comment by petems** [comment]
> I don't know anything about Facter. Can you have it run a command which has a detectable side-effect? e.g. if you can see the stdout from those commands, you could have it run something like echo 'hello'; or if you can see the filesystem on which it operates, you could have it run something like touch /tmp/foo.txt.

Yep, Facter is basically a tool to run commands on a system to get information about various aspects. For example, using a system call to see if SELinux is enabled:

```ruby
sestatus_cmd = '/usr/sbin/sestatus'

Facter.add("selinux_current_mode") do
  confine :selinux => true
  setcode do
    result = 'unknown'
    mode = Facter::Core::Execution.exec(sestatus_cmd)
    mode.each_line { |l| result = $1 if l =~ /^Current mode\:\s+(\w+)$/i }
    result.chomp
  end
end
```

The problem is that there are thousands of these calls being made automatically when you include the library to write what's known as a custom fact. It seems there's a call out there that's waiting for a response, and the changes to the stubbing in that commit mean it's not being stubbed and waiting for a response in some way.

The facter project itself builds fine, it's using it as a library that's causing the failure.

**Comment by floehopper** [comment]
Did you try to identify an individual method call that isn't stubbed when it should be? i.e. by trying to execute a command with a side effect that you can observe.

I've not used it myself, but another way you might be able to narrow things down is by using something like [minitest-bisect](https://github.com/seattlerb/minitest-bisect) to find a single hanging test.

It might also be worth trying the following [Mocha configuration options](http://gofreerange.com/mocha/docs/Mocha/Configuration.html) (probably one at a time):

```ruby
Mocha::Configuration.prevent(:stubbing_method_unnecessarily)
Mocha::Configuration.prevent(:stubbing_non_existent_method)
Mocha::Configuration.prevent(:stubbing_non_public_method)
```

I've double-checked and all the Mocha tests (which are pretty exhaustive) are [passing for Ruby v2.3.1](https://travis-ci.org/freerange/mocha/jobs/166460308).

I really need a way for me to reproduce this bug locally - do you have any suggestions? I'd really appreciate your help.

**Comment by floehopper** [comment]
I've just cloned the voxpupuli/puppet-nginx repo and am able to reproduce the problem locally by running the following single spec: `rspec spec/unit/facter/util/fact_nginx_version_spec.rb:19`. I'm going to try to dig into why this is hanging, but would appreciate any help you can give from your end.

**Comment by petems** [comment]
@floehopper Awesome, I am happy to help any way I can.

**Comment by floehopper** [comment]
I've narrowed things down a bit further. The problem occurs when *both* of the following two lines are used:

```ruby
Facter::Util::Resolution.stubs(:which)
Facter::Util::Resolution.stubs(:exec)
```

The problem also occurs if the order of those two stubs is reversed.

I can also reproduce the problem in the console by simulating what Mocha is trying to do. It is the call to `Facter::Util::Resolution.method(:exec)` which is hanging inside Mocha:

```
irb> require 'facter'
=> true
irb> Facter::Util::Resolution.method(:exec)
=> #<Method: Class(Facter::Core::Execution)#exec>
irb> PrependedModule = Class.new(Module)
=> PrependedModule
irb> Facter::Util::Resolution.singleton_class.send(:prepend, PrependedModule.new)
=> #<Class:Facter::Util::Resolution>
irb> Facter::Util::Resolution.method(:exec)
=> hangs!
```

My suspicion is that there is a problem with the Mocha stubbing in this case when two methods are being stubbed on the same class/module. I will continue to investigate and let you know how I get on.

**Comment by floehopper** [comment]
If I do something similar but with a different class, I don't see the problem:

```
irb> class Foo; def self.bar; end; end
=> :bar
irb> Foo.method(:bar)
=> #<Method: Foo.bar>
irb> PrependedModule = Class.new(Module)
=> PrependedModule
irb> Foo.singleton_class.send(:prepend, PrependedModule.new)
=> #<Class:Foo>
irb> Foo.method(:bar)
=> #<Method: Foo.bar>
```

**Comment by floehopper** [comment]
OK. I now have a *relatively* simple [failing/hanging test](https://github.com/freerange/mocha/blob/issue-272-failing-test-in-ruby-2.3/test/acceptance/issue_272_test.rb#L37-L51) which demonstrates the problem. There seems to have been a change in behaviour in Ruby between v2.2 & v2.3 concerning making (private) module functions public once the module has been used to extend a class. Pretty obscure!!

I've run out of time to look into this for now. Hopefully I'll have some more time to look at it tomorrow.

**Comment by floehopper** [comment]
Hmm. Now I think it might be a bug in Ruby. I don't see why the following shouldn't work and it certainly shouldn't hang!

```ruby
module Foo
  private

  def foo
    "foo"
  end
end

class Bar
  extend Foo

  class << self
    public :foo
  end
end

Bar.foo # => "foo"
Bar.method(:foo) # => #<Method: Class(Bar)#foo>

module Baz
end

class Bar
  class << self
    prepend Baz
  end
end

Bar.method(:foo) # => hangs!
```

**Comment by petems** [comment]
@floehopper Very cool! Thanks for all the time you've put into investigating this, it's super appreciated! 😄

**Comment by floehopper** [comment]
Ruby bug report submitted - https://bugs.ruby-lang.org/issues/12832.

Not quite sure why test only fails in Ruby v2.3, but script fails in Ruby v2.1.3+.

**Comment by floehopper** [comment]
I think my [most recent comment on the Ruby bug report](https://bugs.ruby-lang.org/issues/12832#note-3) explains why the `Facter::Util::Fact` spec only fails in Ruby v2.3, even though a version of the Ruby bug has existed in Ruby since v2.1.3.

**Comment by floehopper** [comment]
@petems:

I have a suggested workaround for your hanging test in Ruby v2.3. Add the following to any tests which stub `Facter::Util::Resolution.which` or `Facter::Util::Resolution.exec` (possibly in your `spec/spec_helper.rb`):

```ruby
# Workaround for freerange/mocha#272 & bug #12832 in Ruby v2.3
class << Facter::Util::Resolution
  def which; super; end
  def exec; super; end
end
```

Obviously it's not ideal, because it's conceivable it _might_ mean that `Facter` behaves differently in your tests version your production code.

Alternatively, if you haven't done it already, I suggest you pin Mocha to v1.1 in your project.

We're probably not going to do more about this bug until we find out more about the bug in Ruby.

I hope that helps.

**Comment by petems** [comment]
@floehopper Thanks for your dedication for helping on this. We'll pin to 1.1 in the meantime, looks like the issue is way bigger than mocha, deep in the Ruby code! 😄

**Comment by floehopper** [comment]
I've just released [a fix](6f1c8b9b6aa4253c8a990befcb89648f09512242) created by @chrisroos in [Mocha v1.2.1](https://rubygems.org/gems/mocha/versions/1.2.1). I believe this fixes the problem you were having. Please re-open this issue if you're not happy with the solution. Thanks for your help in identifying the problem.

**Comment by sarangan12** [comment]
Hi, 

I am trying to use the latest Mocha version - 1.2.1 for testing azure-sdk-for-ruby. But, this results in the test hanging. I have tested this with multiple versions of ruby 2.0.0, 2.1.5, 2.2.0 & 2.3.0. You can find the details here: https://travis-ci.org/Azure/azure-sdk-for-ruby/builds/170262279

**Comment by bastelfreak** [comment]
Hi @sarangan12, there are a lot of bugfixes in ruby231. Could you test that ruby version as well?

**Comment by floehopper** [comment]
@sarangan12: I don't think this is the same bug and so I've opened a new one here: #276.
