### ISSUE TITLE
Consider renaming Mocha::ClassMethod::PrependedModule

### ISSUE THREAD

**Issue by floehopper** [freerange/mocha#279]
We currently re-use this `PrependedModule` in `InstanceMethod` and `AnyInstanceMethod` scenarios. Although this works fine, the name of the module can be a bit confusing when you're debugging.

I'd suggest we do one of the following:
- Define equivalent `PrependedModule`'s for  `InstanceMethod` and `AnyInstanceMethod`
- Define `PrependedModule` in some kind of common base class namespace
- Define `PrependedModule` in just the `Mocha` namespace

This may be related to the idea of extracting a common base class from `ClassMethod`,  `InstanceMethod` and `AnyInstanceMethod` classes and/or using delegation vs inheritance.

**Comment by nitishr** [comment]
Is this still relevant, seeing as there's just one `PrependedModule` now, and `ClassMethod` is already the base class of `InstanceMethod` and `AnyInstanceMethod`?

**Comment by floehopper** [comment]
I think this will be resolved if we merge #381, because `PrependedModule` will then be defined in a more generic namespace.

**Comment by floehopper** [comment]
#381 has been merged and so I'm happy to say this has been addressed. Closing.
