### ISSUE TITLE
Bcrypt problem (hash password)

### ISSUE THREAD

**Issue by hmontes** [freerange/mocha#301]
Hi. I have a problem with Mocha and Bcrypt.

If i use Mocha for test the Application, Bcrypt won't work and don't hash the password.
instead, if i run the app, the hash work perfectly. ¿Where is the problem?

Codes:

Bcrypt thing (I use Mongoose)

```
userSchema.pre('save', function (next) {
  const user = this;
  
  if (!user.isModified('local.password')) return next();
  
  bcrypt.hash(user.local.password, 10).then((hash) => {
    user.local.password = hash;
    return next();
  }).catch((err) => {
    return next(err);
  });
  console.log('bcrypt bypassed?');
  next();
});
```

How i'm running test
package.js
```
...
"scripts": {
    "test": "export NODE_ENV=test || set \"NODE_ENV=test\" && mocha **/**/*.test.js",
    "test-watch": "nodemon --exec 'npm test'",
    "dev": "nodemon server.js"
  },
...
```

I'm using chai-http for the calling. I don't think that's the problem because i'm using the same commands in dev mode.

Thanks

**Comment by floehopper** [comment]
@hmontes: I think you're looking for [mocha.js](https://github.com/mochajs/mocha), this is the Ruby mock object library. Closing.
