### ISSUE TITLE
Stubbed objects not implementing #to_hash are unserializable via ActiveSupport

### ISSUE THREAD

**Issue by drinks** [freerange/mocha#315]
Stubbed real objects are assigned a `@mocha` ivar, which conflicts with `ActiveSupport`'s monkeypatch adding `#as_json` to `Object` in cases where `#to_hash` is not implemented, as seen here: https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/object/json.rb#L51-L59

The `@mocha` ivar turns up in the hash resulting from `#instance_values`, and its value raises `IOError` when sent `:as_json`.

I've worked around this by prepending #instance_values under test to strip the `mocha` key with some success. Happy to put together a PR, but not really sure what the most reasonable fix might be.

**Comment by floehopper** [comment]
@drinks:

Thanks for opening this issue. It feels closely related to #285 (and somewhat related to #81) which we have yet to resolve.

To make this work seamlessly in the general case, we'd want the `@mocha` instance variable to be invisible to other library/application code (like Active Support), but visible to Mocha library code. I'm not sure there's an easy solution for this. As per my last comment in #81, I'm leaning towards failing fast if attempting to serialize an object with stubbed methods.

Do you have a simple example test which demonstrates why you might want to do what you describe? I'm wondering whether we might be able to suggest an alternative approach...?

**Comment by floehopper** [comment]
Closing in favour of #328.
