### ISSUE TITLE
Consider dropping support for older versions of Ruby

### ISSUE THREAD

**Issue by floehopper** [freerange/mocha#325]
Ideally come up with rules to define how this works.

Some useful references:

* https://github.com/rspec/rspec/issues/25
* https://github.com/rspec/rspec-rails/pull/1967

**Comment by floehopper** [comment]
[Extended maintenance of Ruby versions 1.8.7 and 1.9.2 will end on July 31, 2014](https://www.ruby-lang.org/en/news/2014/07/01/eol-for-1-8-7-and-1-9-2/).

**Comment by nitishr** [comment]
Why aren't we dropping support for at least 1.8.7 already? It hasn't even been possible for me to run `bundle exec rake` with 1.8.7 due to the difficulty of installing the right combination of gems and libraries.

This would also help clean up some code as well as close some open issues.

**Comment by floehopper** [comment]
> Why aren't we dropping support for at least 1.8.7 already?

No good reason. I think I was just agonising over how to deal with it within the confines of semantic versioning. I've just done this in c5f8496d5102445de315a10efc385209a962bdc1.

> It hasn't even been possible for me to run bundle exec rake with 1.8.7 due to the difficulty of installing the right combination of gems and libraries.

That's odd. Did you try deleting your `Gemfile.lock` before running `bundle install`? That seems to work for me locally.

> This would also help clean up some code as well as close some open issues.

I agree. Thanks for the prompt!

**Comment by floehopper** [comment]
[Extended maintenance of Ruby v1.8.7 ended on 31 Jul 2014][1] and Mocha support for Ruby v1.8 has been [deprecated since v1.10][2]. Recent work in #534 has run into problems with files containing keyword arguments not being parsable by Ruby v1.8 and so I think the time has come to drop support.

[1]: https://www.ruby-lang.org/en/news/2014/07/01/eol-for-1-8-7-and-1-9-2/
[2]: https://github.com/freerange/mocha/commit/c5f8496d5102445de315a10efc385209a962bdc1

**Comment by floehopper** [comment]
I've just dropped support for Ruby v1.8 in #536. There's still some question about whether that should be a minor or major version release, but that decision can wait for now.

**Comment by floehopper** [comment]
[Support for Ruby version 1.9.3 ended on February 23, 2015](https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/).

**Comment by floehopper** [comment]
> I've just dropped support for Ruby v1.8 in #536. There's still some question about whether that should be a minor or major version release, but that decision can wait for now. 

Hmm. I'm not sure how conscious the decision was, but the dropping of support for Ruby v1.8 ended up being in [a minor version bump](https://github.com/freerange/mocha/blob/v1.15.0/RELEASE.md#external-changes)!

**Comment by floehopper** [comment]
From [the rspec-rails versioning strategy](https://github.com/rspec/rspec-rails/blob/90779f31bb8a203ec3f80a841e1ed443d674bcff/rfcs/versioning-strategy.md#approach):

> For the purposes of this versioning strategy, we consider removing a Rails or Ruby version to be a breaking change.

**Comment by floehopper** [comment]
For Mocha v2.0, I'm happy that we should drop support for Ruby versions earlier than Ruby v2.0.

* Support for Ruby < v1.9 was deprecated in c5f8496d5102445de315a10efc385209a962bdc1, dropped in ddb5d67246f8417402d02533f988720281cc0a34, and released in Mocha v1.15.0.
* Support for Ruby < v2.0 was deprecated in d752f09482848345b9c786365f9ad5eb3a3c2ac7, dropped in 26c4ae1ecd1057751685a5474932d05701a2c294, and will be released in Mocha v2.0.

I don't think it's worth keeping this issue around any longer. If we want to consider dropping support for later versions of Ruby we can always create a new issue. Closing.
