### ISSUE TITLE
Consider adding "and_call_original" to .expects

### ISSUE THREAD

**Issue by sekmo** [freerange/mocha#334]
I found myself writing some tests where I wanted to check a method call with the right parameters, but I wanted not to stub the returning value. Why don't add something like "and_call_original" to mocha? 

(https://relishapp.com/rspec/rspec-mocks/docs/configuring-responses/calling-the-original-implementation)

**Comment by floehopper** [comment]
@sekmo:

Thanks for your interest in Mocha.

I hope you don't mind, but I've updated the URL in your comment to link to [a more up-to-date version of RSpec's documentation][1].

In answer to your question, Mocha is intended to be used in *unit* tests for the [Mock Object][] or [Test Stub][] types of [Test Double][], not the [Fake Object][] or [Test Spy][] types. Although it would be possible to extend Mocha to allow the implementation of fakes and spies, I'd prefer to keep it focussed on mocks and stubs. I think providing a fully-fledged solution for fakes and/or spies would be a lot of work and this isn't something I have time for right now.

That being said, I would be open to the idea of a Mocha extension which allowed this kind of functionality and I would be prepared to help by providing the necessary integration API/hooks.

So I'm afraid I'm going to close this issue as "wont-implement".

[Mock Object]: http://xunitpatterns.com/Mock%20Object.html
[Test Stub]: http://xunitpatterns.com/Test%20Stub.html
[Test Double]: http://xunitpatterns.com/Test%20Double.html
[Fake Object]: http://xunitpatterns.com/Fake%20Object.html
[Test Spy]: http://xunitpatterns.com/Test%20Spy.html

[1]: https://relishapp.com/rspec/rspec-mocks/docs/configuring-responses/calling-the-original-implementation

**Comment by floehopper** [comment]
Relates to #330.
