### ISSUE TITLE
How come .then doesn't work like an implicit sequence?

### ISSUE THREAD

**Issue by jmoses** [freerange/mocha#34]
I always expect:

``` ruby
    object.expects(:method).returns(false).then.returns(true)
```

to work equivalently to:

``` ruby
    seq = sequence("name")
    object.expects(:method).returns(false).in_sequence(seq)
    object.expects(:method).returns(true).in_sequence(seq)
```

How come it doesn't?  It always throws me.

-jon

**Comment by floehopper** [comment]
The [documentation](https://mocha.jamesmead.org/Mocha/Expectation.html#then-instance_method) was improved in 4e28497a0df59b86537cdc689ef3cd11ea6c7c3e (Mar 2021) where overloads were added for each of the two usages. Belatedly closing.
