### ISSUE TITLE
Object.mocha_inspect not compatible with classes that define a 'format' method

### ISSUE THREAD

**Issue by hoffmanilya** [freerange/mocha#342]
It looks like setting an expectation on a class that defines a `format` method results in an `ArgumentError`. 

Take the following test case:

```
class ObjectTest < ActiveSupport::TestCase

  class DummyClass
    attr_reader :format
  end

  test 'dummy class expectations' do
    dummy_class = DummyClass.new
    dummy_class.expects(:foo)
  end

end
```

Running it:

```
ObjectTest
  test_dummy_class_expectations                                  ERROR (0.13s)
ArgumentError:         ArgumentError: wrong number of arguments (2 for 0)

```

This is because `mocha_inspect` calls the `format` method:

```
def mocha_inspect
  address = __id__ * 2
  address += 0x100000000 if address < 0
  inspect =~ /#</ ? "#<#{self.class}:0x#{format('%x', address)}>" : inspect
end
```

Would you consider changing that to call `Kernel.format` directly? This way it won't interfere with any instance methods on the object being inspected. If so, let me know and I'll be happy to put together a PR.

**Comment by floehopper** [comment]
@hoffmanilya Thanks for reporting this issue. It'd be great if you could put a PR together to fix it by calling `Kernel.format` directly. Thanks! 👍
