### ISSUE TITLE
Stubbing methods on classes that dynamically define methods don't work anymore

### ISSUE THREAD

**Issue by rafaelfranca** [freerange/mocha#432]
If the `respond_to?` of an object depends on its internal state and we use `any_instance` it is not possible to stub any method of this object.

```irb
>> require 'mocha/api'
=> true
>> class Foo
>>   def initialize(attrs = {})
>>     @attributes = attrs
>>     end
>>   def respond_to?(method, *args)
>>     @attributes.key?(method) ? @attributes[method] : super
>>     end
>>   end
=> :respond_to?
>> include Mocha::API
=> Object
>> Foo.any_instance.stubs(:foo)
Traceback (most recent call last):
       12: from /opt/rubies/2.6.5/bin/irb:23:in `<main>'
       11: from /opt/rubies/2.6.5/bin/irb:23:in `load'
       10: from /opt/rubies/2.6.5/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        9: from (irb):13
        8: from /Users/rafaelfranca/.gem/ruby/2.6.5/gems/mocha-1.10.0/lib/mocha/object_methods.rb:127:in `stubs'
        7: from /Users/rafaelfranca/.gem/ruby/2.6.5/gems/mocha-1.10.0/lib/mocha/argument_iterator.rb:13:in `each'
        6: from /Users/rafaelfranca/.gem/ruby/2.6.5/gems/mocha-1.10.0/lib/mocha/object_methods.rb:129:in `block in stubs'
        5: from /Users/rafaelfranca/.gem/ruby/2.6.5/gems/mocha-1.10.0/lib/mocha/mockery.rb:131:in `on_stubbing'
        4: from /Users/rafaelfranca/.gem/ruby/2.6.5/gems/mocha-1.10.0/lib/mocha/mockery.rb:154:in `check'
        3: from /Users/rafaelfranca/.gem/ruby/2.6.5/gems/mocha-1.10.0/lib/mocha/mockery.rb:132:in `block in on_stubbing'
        2: from /Users/rafaelfranca/.gem/ruby/2.6.5/gems/mocha-1.10.0/lib/mocha/class_methods.rb:30:in `respond_to?'
        1: from (irb):7:in `respond_to?'
NoMethodError (undefined method `key?' for nil:NilClass)
```

This happen because we are trying to `allocate` the object what leaves the object with the wrong internal state. It is common to people to setup all internal state of an object using the `initialize` method, so I don't think anyone setup internal state of objects defining a `allocate`.

**Comment by nitishr** [comment]
Thank you for reporting, @rafaelfranca.

I've just checked with v1.9 and you'd get the same error on that version with `Mocha::Configuration.{warn_when,prevent}(:stubbing_non_{existent,public}_method)`

The behavior that's changed is that you wouldn't get the error under the default configuration, because the method_exists? check wouldn't be done when stubbing non-public/existent methods is allowed.

I'm working on a quick fix to make the behavior compatible with the older version. A proper fix even for the earlier 'broken' behavior would possibly need a design change, if it's even possible at all.

**Comment by rafaelfranca** [comment]
Thank you! Yeah, I noticed that 1.9 was also broken when those configs were enabled.

One of the sources of this behavior is Rails. I find very hard to justify making a change to the framework because a mock library. I'll check how rspec-mock and minitest-mock are dealing with this case, if they are. If they are not, I'll change Rails.

**Comment by floehopper** [comment]
@rafaelfranca Thanks for reporting this. I've merged the fix and I'll release it as soon as I can.

**Comment by floehopper** [comment]
@rafaelfranca I've just released [v1.10.1](https://rubygems.org/gems/mocha/versions/1.10.1). Please can you see whether that's fixed your problem?

**Comment by rafaelfranca** [comment]
Thank you folks. That fix the issue.

**Comment by floehopper** [comment]
@rafaelfranca Excellent. Thanks for letting us know.

@nitishr Thanks again for fixing this!

**Comment by floehopper** [comment]
@nitishr Is it worth opening a new issue for the more fundamental problem mentioned in the earlier comments? I have some ideas on how to fix it.

**Comment by nitishr** [comment]
Yes, I think it'd be worth. Would you do it or should I?

**Comment by floehopper** [comment]
> Yes, I think it'd be worth. Would you do it or should I?

Done: #435.
