### ISSUE TITLE
Race condition when using `stubs` in JRuby

### ISSUE THREAD

**Issue by fzakaria** [freerange/mocha#461]
A common example of using _mocha_ is to stub Time to return a fixed time.
For instance,
```ruby
now = Time.now
Time.stubs(:now).returns(now)
```

However if there is a separate thread running which tries to invoke the stubbed method (specifically on non-GIL interpreters like JRuby), we've encountered a race condition in that the mocha will raise an exception that the expectations have not been met.

here is a simple example:

```ruby
  def test_mocha_thread_safety
    Thread.new do
      500.times do
        # just loop and call Time#now a bunch while the thread above keeps stubbing
        Time.now
      end
    end

    now = Time.now
    500.times do
      # the two mechanisms involve different stubbing code, wso lets test both
      Time.stubs(:now).returns(now)
    end

  end
```

Looking through the code; the result seems to be due to the `mock.rb` not being protected with a critical section.

```ruby
    def stubs(method_name_or_hash, backtrace = nil)
      iterator = ArgumentIterator.new(method_name_or_hash)
      iterator.each do |*args|
        method_name = args.shift
        ensure_method_not_already_defined(method_name)
        expectation = Expectation.new(self, method_name, backtrace)
        expectation.at_least(0)
        expectation.returns(args.shift) unless args.empty?
        @expectations.add(expectation)
      end
    end
```

Specifically if `@expectations.add(expectation)` is not executed but the method has been _stubbed_, then the `method_missing` in _mock_ will raise an exception since there is no expectation to match against.

stubs + method_missing need to share the same mutex and become a critical section
or
method_missing should not raise if expectations is empty

**Comment by floehopper** [comment]
@fzakaria Sorry for the slow response - I've been busy with client work. Thanks for raising this issue and for opening a PR in an attempt to fix it. I'll have a proper look at it as soon as I can.

**Comment by floehopper** [comment]
While I am sympathetic to the idea of making Mocha more thread-safe, I suspect it's no small undertaking. I have previously created an experimental branch (see #361) to explore the idea. However, that was specifically about allowing different test methods to be run in different threads and not interfere with each other. The idea that the code under test might be executed by a different thread than the test makes things even more complicated!

I think it would help me if you could explain why you want to have a test which executes in one thread but where the code under test is executed in another thread. I'm guessing you are stubbing within some kind of high-level integration or acceptance test - is that correct? If so, you might be better off wrapping the call to `Time.now` with some kind of class, e.g. `Clock`, and then inject a [Fake Object](http://xunitpatterns.com/Fake%20Object.html) version of the `Clock` object for the duration of the test. Alternatively, I don't know whether the [Timecop gem](https://rubygems.org/gems/timecop) might better support your use case.

I'm not sure whether it's relevant to your specific example about stubbing `Time.now`, but in case it's useful, there's some good advice about using mock objects in a multi-threaded environment in [this jMock documentation](http://jmock.org/threads.html), e.g.

> The root of the problem is trying to use mock objects for integration testing. Mock objects are used for unit testing in the traditional sense: to test units in isolation from other parts of the system. Threads, however, by their very nature, require some kind of integration test. Concurrency and synchronisation are system-wide concerns and code that creates threads must make use of operating system facilities to do so.
>
> A solution is to separate the object that needs to run tasks from the details of how tasks are run and define an interface between the two. We can test the object that needs to run tasks by mocking the task runner, and test the implementation of the task runner in integration tests.

**Comment by fzakaria** [comment]
Thank you @floehopper for the thorough response.

Your assumption regarding the integration test use of mocha is correct. I'm familiar with the fallbacks/pitfalls of using stubbing/mocking for acceptance testing however I'm working with a legacy codebase that already makes heavy use of it. We are slowly moving towards a Clock idiom however I was trying to seek a middle ground solution in the interim.

We can close the pull-request since it sounds like my solution is not appropriate.

The Timecop gem is interesting too -- looks like they monkey patch Time upfront once so it might be _thread safe_ for usecase (i.e. doesn't suffer non-critical section undefine -> define method block)

**Comment by floehopper** [comment]
@fzakaria Cool. Thanks for all your input. 👍
