### ISSUE TITLE
Cannot match keyword argument with "anything"

### ISSUE THREAD

**Issue by lukeredpath** [freerange/mocha#470]
👋 James!

I have a method that takes one positional argument and one keyword argument. I only want to match an expectation based on the positional argument.

The following example works fine:

```ruby
mock = mock('thing')
mock.expects(:do_something).with('foo', named_param: 'bar')
mock.do_something('foo', named_param: 'bar')
```

The following fails with an unexpected invocation error:

```ruby
mock = mock('thing')
mock.expects(:do_something).with('foo', named_param: anything)
mock.do_something('foo', named_param: 'bar')
```

Error output:

```
unexpected invocation: #<Mock:thing>.do_something("foo", {:named_param => "bar"}        unsatisfied expectations:
    - expected exactly once, invoked never: #<Mock:thing>.do_something("foo", {:named_param => anything})
```

Expected result: both examples behave identically.

Ruby: ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin18]
Mocha: 1.11.2

Run using Rails 6 and Minitest.

**Comment by floehopper** [comment]
@lukeredpath: Hi there! Sorry for the slow reply - I'm currently on holiday. As with any Ruby receiver method, keyword arguments are supplied to the method as a `Hash`. You can actually see this from the "unexpected invocation" error message in your error output above. So while it might not be completely intuitive, you can achieve what you want by using a matcher like [`has_entry`][1] along the following lines:

```ruby
mock.expects(:do_something).with('foo', has_entry(named_param: anything))
```

I can see why you would expect your version to work. However, when keyword arguments were first introduced I don't think there was a way for a receiver method implementation to tell the difference between a `Hash` value being passed in a standard argument vs one or more keyword arguments.

However, I've just noticed [`Method#parameters`][2] which might allow us to do something a bit smarter with keyword arguments. I've opened [a new issue to investigate this possibility][3]. I've also opened [a new issue to add some documentation specifically about parameter matching for keyword arguments][4].

I'm going to close this issue. Please feel free to re-open it if you don't think I've fully addressed your concerns.

[1]: https://mocha.jamesmead.org/Mocha/ParameterMatchers.html#has_entry-instance_method
[2]: https://ruby-doc.org/core-2.6.5/Method.html#method-i-parameters
[3]: https://github.com/freerange/mocha/issues/472
[4]: https://github.com/freerange/mocha/issues/471

**Comment by lukeredpath** [comment]
Thanks James, that explains it nicely.

**Comment by floehopper** [comment]
👍

**Comment by nitishr** [comment]
> [...] you can achieve what you want by using a matcher like [`has_entry`](https://mocha.jamesmead.org/Mocha/ParameterMatchers.html#has_entry-instance_method) along the following lines:
> 

More precisely, you can achieve _something close to_ what you want that should work for most practical purposes. It may not be exactly what you'd expect. For instance, the expectation below:

> ```ruby
> mock.expects(:do_something).with('foo', has_entry(named_param: anything))
> ```
> 

will also be satisfied by a call like

```ruby
mock.do_something('foo', named_param: 'bar', you_may_not_have_expected_this_param: 'baz')
```

> However, I've just noticed [`Method#parameters`](https://ruby-doc.org/core-2.6.5/Method.html#method-i-parameters) which might allow us to do something a bit smarter with keyword arguments.

From a little bit of analysis I've done, this may not be quite useful or relevant, but it should still be fairly easy to better support the expectation described originally by @lukeredpath (or something close to it - e.g. a stricter alternative to has_entry/has_entries that'll match the exact set of keyword arguments).

**Comment by nitishr** [comment]
@lukeredpath I've just opened #475 to address this. It isn't exactly the API you were expecting (although I think that's achievable too). Would be great to have your feedback.

**Comment by floehopper** [comment]
@nitishr You are quite right about my workaround not being exactly what @lukeredpath was trying to do. However, I think you could use [`Mocha::ParameterMatchers#equals`][1] to achieve more exactly what he wants...

```ruby
    mock = mock('thing')
    mock.expects(:do_something).with('foo', equals(named_param: 'bar'))
    mock.do_something('foo', named_param: 'bar')
```

Does that make sense? And does that make #475 redundant / less useful?

[1]: https://mocha.jamesmead.org/Mocha/ParameterMatchers.html#equals-instance_method

**Comment by floehopper** [comment]
Oh, no. Ignore my last comment - I wasn't thinking straight!

**Comment by brunofacca** [comment]
For future Googlers, the following works For multiple keyword arguments:
```
mock.expects(:do_something).with('foo', has_entries(named_param: anything, other_named_param: :foo))
```
