### ISSUE TITLE
Improve documentation for parameter matching of keyword arguments

### ISSUE THREAD

**Issue by floehopper** [freerange/mocha#471]
Add some documentation to explain how to do parameter matching of keyword arguments. See #470 for more details.

**Comment by floehopper** [comment]
With the introduction of the new strict keyword argument matching in #554 and the deprecation warnings added in #563, I'm hoping that parameter matching of keyword arguments should work fairly intuitively. However, it might be worth adding to [the documentation of `Expectation#with`](https://mocha.jamesmead.org/Mocha/Expectation.html#with-instance_method), possibly with an example or two...?

@wasabigeek What do you think?

**Comment by floehopper** [comment]
Addressed in fed6808da2d02354a091fe25b9811dad09e785af & 8d8f881d98a0f53fec12cd1a27be2260f8e086de. Closing.

**Comment by wasabigeek** [comment]
Sorry for the delay! I think it makes sense 👍
