### ISSUE TITLE
Change in partial expectation evaluation time?

### ISSUE THREAD

**Issue by srvance** [freerange/mocha#473]
It appears that in 1.10.0, the time at which partial expectations start recording changed, but I don't see anything in the release notes that explains what I'm seeing. I suspect that <1.10.0, they started recording at the time of partial definition, but >=1.10.0 they start recording only when they've been finalized with a quantifier.  For example, see this simplified snippet of some code found in the wild:

```
before do
  exp = Foo.any_instance.expects(:action)
end

it 'invokes' do
  Foo.action
  exp.twice
  Foo.action
end
```

Moving the `twice` up a line works regardless of version.

Is this expected? Is there another explanation?

**Comment by floehopper** [comment]
@srvance Thanks opening this issue. I'm on holiday at the moment, so it might be a while before I can investigate. We have been doing a bunch of internal refactoring, so that might explain the change in behaviour, although we worked pretty hard to avoid any such change.

@nitishr I don't suppose you have time to investigate this...?

**Comment by srvance** [comment]
No problem. I just wanted to bring it to your attention since it didn't seem documented. I can work around it by reordering the statements. This is part of a big Rails upgrade project.

Historically, it appears to have gotten this way by someone mechanically moving the first `Foo.action` from a `before` to the `it` as needs changed within the `describe`.

**Comment by nitishr** [comment]
Hi @srvance. Thank you for reporting. I've just tried out the scenario you've described under v1.9.0 and master, and noticed the difference. I'll investigate this.

Could you please describe the impact this is having on you - it'll help me understand both the need for a 'fix' and the urgency for it.

**Comment by srvance** [comment]
No urgency.

It took awhile to figure out why a few tests were suddenly failing. The mocha update was incidental to updating other gems, but it was a big jump (1.2.1 -> 1.11.2).

I'd just vote for a troubleshooting documentation item or perhaps a deprecation warning if the situation can be recognized. Once I figured it out, it's easy to fix. As you can imagine, in a more complex context, there's also archeology involved in determining whether the test was written intentionally and so forth. The biggest opportunity is just saving others possibly a good bit of confusion and investigative time.

**Comment by nitishr** [comment]
OK, I've nailed the issue down to 59454a83648f76e46918779f7dd39a34927cff2c. When you qualify the expectation with a (different) quantifier, the `Cardinality` gets changed, and with it, the prior invocations it had recorded get lost/forgotten.

I'll work on a fix for this tomorrow.

**Comment by srvance** [comment]
Interesting. So in this case, there was no explicit quantifier, which counts as a default quantifier that gets discarded, resetting the recordings, when the explicit quantifier is added?

**Comment by nitishr** [comment]
@srvance Yes, you've got it right.

@floehopper I've issued #474 to fix this regression.
