### ISSUE TITLE
Ensure developers can run `yard doc` locally against the gem source code

### ISSUE THREAD

**Issue by floehopper** [freerange/mocha#479]
This came out of the discussion in #477. It seems like a legitimate requirement that a developer should be able to run `yard doc` locally against the gem source code and not see errors or warnings.

The following issues/PRs might also be relevant:  #422, #423, #429.

**Comment by olleolleolle** [comment]
Just to be clear, running yard doc on master is without warnings at the moment.

(Any warnings I experienced were in a released gem, the latest  release, not in code on GitHub.)

**Comment by floehopper** [comment]
I have yard v0.9.24 installed and I can run `MOCHA_GENERATE_DOCS=1 yard doc` without any warnings or errors. So I'm not sure there's anything to do here. Closing.
