### ISSUE TITLE
Stubbing a method for only one parameter, others to call actual method

### ISSUE THREAD

**Issue by Bennet-Sunder** [freerange/mocha#483]
Very similar to the below question, how would you do this with mocha. 

https://stackoverflow.com/questions/16559374/mocha-stubbing-method-with-specific-parameter-but-not-for-other-parameters

**Comment by Bennet-Sunder** [comment]
okay turns out it can't be done https://stackoverflow.com/questions/21715174/ruby-mocha-is-there-an-equivalent-to-rspec-mocks-and-call-original

**Comment by floehopper** [comment]
@Bennet-Sunder Yes, that's correct - thanks for answering your own question!

FWIW If you're testing code you own (i.e. you have the power to change it), you might want to think about changing the design of the code so you don't need to do this. If you can post some code showing what you're trying to do, I'd be happy to try to help.

**Comment by Bennet-Sunder** [comment]
@floehopper so what I want to do is I have a method say `print_name(user)`  what I want to do is if this method is called with parameter `user = hello` it should return false and if it is called with say any other parameter then it should call the actual implementation.

**Comment by floehopper** [comment]
Yes, I understand *what* you're trying to do, but I wonder if there might be a way to change the implementation which makes *both* makes testing easier (i.e. avoids the need to do what you're currently trying to do) *and* makes the code clearer. I'd need a bit more context and ideally the actual code to be able to make any useful suggestions. This is probably a bit academic, so no worries if you don't want to pursue it any further.

**Comment by Bennet-Sunder** [comment]
@floehopper I was able to get it resolved for now. thanks!
