### ISSUE TITLE
Documentation website returning 404 Not Found

### ISSUE THREAD

**Issue by jamesbebbington** [freerange/mocha#486]
Visiting https://mocha.jamesmead.org, as linked to throughout the README as the Official Documentation site, returns a `404 Not found`. Expected many pages of delightful docs.

**Comment by jamesbebbington** [comment]
Documentation is available at https://www.rubydoc.info/gems/mocha for anyone who needs it.

**Comment by floehopper** [comment]
@jamesbebbington Thanks for reporting this. I recently changed the default branch from `master` to `main` and deleted the `master` branch. However, it turns out that GitHub Pages silently disabled itself when I did this. It should be fixed now. Closing.
