### ISSUE TITLE
Stub and yield passed block

### ISSUE THREAD

**Issue by andyw8** [freerange/mocha#495]
I was looking for way to stub a method and simply yield the block.

After trying some awkward approaches, I discovered this works with simply `stubs(:foo).yields`, but this form without arguments doesn't seem be documented:

https://www.rubydoc.info/github/floehopper/mocha/Mocha%2FExpectation:yields

If this is a valid use then I can submit a PR to update the docs.

**Comment by floehopper** [comment]
@andyw8 The `*parameters` in the `Mocha::Expectation#yields(*parameters) ⇒ Expectation` signature in the docs means that you can list zero, one, or more parameters. However, perhaps people aren't familiar enough with this notation. I'd be happy to include another _example_ in the docs which has no parameters being yielded to the block if you think that would make things clearer.

**Comment by andyw8** [comment]
Yeah, I understand that `*parameters` can mean zero, but it felt a little like 'undocumented behaviour'.

**Comment by andyw8** [comment]
For context here's where I'm using it:

https://github.com/Shopify/shopify-app-cli/blob/1a5b2d72406addc86a5412ab2be19f55c8e2daa5/test/shopify-cli/commands/config_test.rb#L12

**Comment by nitishr** [comment]
> @andyw8 The `*parameters` in the `Mocha::Expectation#yields(*parameters) ⇒ Expectation` signature in the docs means that you can list zero, one, or more parameters. However, perhaps people aren't familiar enough with this notation. I'd be happy to include another _example_ in the docs which has no parameters being yielded to the block if you think that would make things clearer.

There already is such an example: https://github.com/freerange/mocha/blob/0085b60f62da979ad6923d5c3cd0ae35893de876/lib/mocha/expectation.rb#L274. Perhaps it's not clear enough because of mixing yields and returns, and isn't explicit about 'no/without parameters'.

**Comment by floehopper** [comment]
> Perhaps it's not clear enough because of mixing yields and returns, and not being explicit about 'no/without parameters'.

Thanks, @nitishr. Yes, that was my assumption too. I'm always keen to improve the documentation and so if separating the examples makes things clearer then I'm in favour of it. In fact in this case, it might be clearer not to call `Expectation#returns` in any of the examples for `Expectation#yields`. What do you think?

**Comment by nitishr** [comment]
Yeah, I think focusing on just the `yields` without mixing with `returns` would be clearer. I'm happy to update the example(s) if you'd like.

**Comment by floehopper** [comment]
> Yeah, I think focusing on just the `yields` without mixing with `returns` would be clearer. I'm happy to update the example(s) if you'd like.

Thanks. I've already merged something along those lines in d59081262f64a872d6ec5ec9dc9c0d7be57b643a.
