### ISSUE TITLE
How to stub recursive calls?

### ISSUE THREAD

**Issue by hyunwoona** [freerange/mocha#503]
Hi,

I have trouble stubbing recursive calls with Mocha.
A simplified version of the method I am trying to stub looks like this:

```
def calculate(a, b, should_recurse=true)
  # ...
  if should_recurse
    calculate(a, b, false)
  end
end
```

I want to mock just the recursive invocation of `calculate`.
I've tried `TestClass.expects(:calculate).with(anything, anything, false)` but this stubs both recursive and non-recursive `calculate` calls.

Is there a way to stub just the recursive calls without touching the original code?

**Comment by floehopper** [comment]
When a method is stubbed the original implementation is *replaced* with an implementation provided by Mocha. You are then responsible for defining the behaviour of that implementation. There is currently no way to invoke the original implementation of the method once you've stubbed it, so I don't think what you want to do is currently possible. In the README [it says](https://mocha.jamesmead.org/#intended-usage):

> Although it would be possible to extend Mocha to allow the implementation of fakes and spies, we have chosen to keep it focused on mocks and stubs.

And I think what you want to do is something more like one of these which are not supported by Mocha:

* http://xunitpatterns.com/Test%20Spy.html
* http://xunitpatterns.com/Fake%20Object.html

**Comment by floehopper** [comment]
One way you might be able to do this would be if you could separate the recursive version of the method from the non-recursive version, i.e. some thing along these lines:

```ruby
def calculate_with_recursion(a, b)
  # ...
  calculate_without_recursion(a, b)
end

def calculate_without_recursion(a, b)
  # ...
end
```

Then you should be able to stub just the `calculate_without_recursion` method.

**Comment by floehopper** [comment]
@hyunwoona: I hope my explanations have helped. I've opened #504 to investigate improving the documentation to make things clearer in this area. I'm going to close this issue, but feel free to reopen it if you have more questions.
