### ISSUE TITLE
[Question] Is it possible to have mocha not display ActiveRecord column information in its output?

### ISSUE THREAD

**Issue by josh-m-sharpe** [freerange/mocha#510]
When mocha detects a failed expectation on a class that inherits from ActiveRecord::Base it displays a message like this:

```
unexpected invocation: User(col1: integer, col2: integer, col3: integer, col4: integer, col5: integer, col6: integer, col7: integer, col8: integer, col9: integer).some_method('options', 'etc')
```

I (personally) find all of that column information noisy and can't say I've ever had a use for it.  It can be a heck of a lot of output for large tables and can easily dwarf the important information (the method call and params that are passed).

Is there a way to disable that output? I suppose I would prefer that it just be removed, so the message would look like this:

```
unexpected invocation: User.some_method('options', 'etc')
```

Cheers and Thank you!

**Comment by floehopper** [comment]
It's pretty old, so the code might be out-of-date, but you could try the solution suggested in #151.

**Comment by floehopper** [comment]
@josh-m-sharpe I'd be interested to hear whether this works, but since this issue is already captured in #151, I'm going to close this issue.

**Comment by josh-m-sharpe** [comment]
@floehopper that suggestion works exceedingly well. I threw it in test_helper.rb and output is so much more concise!  Thanks!

**Comment by floehopper** [comment]
@josh-m-sharpe Glad it all worked out well. 👍
