### ISSUE TITLE
[Question] Can API.mock be called with a block?

### ISSUE THREAD

**Issue by qr8r** [freerange/mocha#517]
There are places in the documentation which show the `mock` method being called with a block

https://github.com/freerange/mocha/blob/main/lib/mocha/api.rb#L202-L206

I love the idea of this syntax. It doesn't seem to work for me however, and reading the source code it doesn't look like that method is capturing the block or yielding when it is called? 

Is the documentation wrong?

**Comment by qr8r** [comment]
I guess this is deprecated behaviour 
https://github.com/freerange/mocha/pull/418

**Comment by floehopper** [comment]
> I guess this is deprecated behaviour
> #418

Yes, it is deprecated behaviour and the documentation is out-of-date. See #290 for details. Thanks for drawing this to our attention. I've opened [a new issue](https://github.com/freerange/mocha/issues/518) to capture updating the docs.

Would using `Object#tap` help you do what you want?

Anyway, we're not going to reinstate this deprecated behaviour and so I'm going to close this issue. Hope that's OK.
