### ISSUE TITLE
Composability of matchers?

### ISSUE THREAD

**Issue by zenspider** [freerange/mocha#545]
This is more a tech support question than a issue... Is there a trick to getting the matchers to compose in various ways? What we're trying:

```ruby
Thingy.expects(:create!).with(has_entries(
  k0: :v0,
  k1: includes("support/accounts/settings"),
  k2: :v2))
```

doesn't seem to work (tho, the whole test is so damn complex... who knows what's really going wrong...

Basically, the `v1` value is binary & too complex/variable and was causing flaky tests... so I thought let's just try the bare minimum check there, but it seems like the matchers don't compose in some areas? In some they're clearly called out that you can do so but maybe not `has_entries` ? How to better tell? Or, do you have suggestions on how to do something like the above? 

I suppose we can always punt and use the block form of `with`?

**Comment by floehopper** [comment]
@zenspider

Good question! Of the top of my head, I'm not sure I could say with any level of certainty what will and won't work - the code was written so long ago! However, I'm fairly confident the Hash-related matchers tolerate at least some level of nesting.

I just tried out your example and it seems to work:

```ruby
require 'minitest/autorun'
require 'mocha/minitest'

class Thingy
  def self.create!(hash)
  end
end

class FooTest < Minitest::Test
  def test_create_with_matching_params
    Thingy.expects(:create!).with(has_entries(
      k0: :v0,
      k1: includes("support/accounts/settings"),
      k2: :v2)
    )

    Thingy.create!({
      k0: :v0,
      k1: 'foo/support/accounts/settings/bar',
      k2: :v2
    })
  end

  def test_create_with_non_matching_params
    Thingy.expects(:create!).with(has_entries(
      k0: :v0,
      k1: includes("support/accounts/settings"),
      k2: :v2)
    )

    Thingy.create!({
      k0: :v0,
      k1: 'support/accounts/profile',
      k2: :v2
    })
  end
end
```

```
> bundle exec ruby foo.rb
Run options: --seed 48251

# Running:

.F

Finished in 0.000800s, 2500.0000 runs/s, 1250.0000 assertions/s.

  1) Failure:
FooTest#test_create_with_non_matching_params [foo.rb:31]:
unexpected invocation: Thingy.create!(:k0 => :v0, :k1 => "support/accounts/profile", :k2 => :v2)
unsatisfied expectations:
- expected exactly once, invoked never: Thingy.create!(has_entries({:k0 => :v0, :k1 => includes("support/accounts/settings"), :k2 => :v2}))


2 runs, 1 assertions, 1 failures, 0 errors, 0 skips
```

So perhaps there is something else wrong in the actual test as you suggested...?

I've opened #546 as a reminder to improve the documentation in this area. I've not got loads of time right now, so it might be a while before I get to it. If you have any more specific questions, let me know.

**Comment by floehopper** [comment]
@zenspider I'm going to close this for now, but feel free to re-open if you have more questions.
