### ISSUE TITLE
Mocha is incompatible with minitest v5.19 and later

### ISSUE THREAD

**Issue by kyrofa** [freerange/mocha#614]
[Minitest has removed](https://github.com/minitest/minitest/blob/master/History.rdoc) the ancient MiniTest compatibility layer that Mocha has been relying on unless the user defines the `MT_COMPAT` environment variable. See [the commit](https://github.com/minitest/minitest/commit/a2c6c18570f6f0a1bf6af70fe3b6d9599a13fdd6) for more details.

Seems that Mocha should move to using `Minitest` instead?

**Comment by floehopper** [comment]
@kyrofa:

Thanks for the heads up, although I'm a bit confused about what's broken. I just manually ran [the weekly build](https://app.circleci.com/pipelines/github/freerange/mocha/415/workflows/121f5ace-9133-4d22-a073-85a69cde57dd) which tries to pick up on incompatibilities like this, but nothing failed even though [the job using the latest Minitest gem seems to have used v5.19.0](https://app.circleci.com/pipelines/github/freerange/mocha/415/workflows/121f5ace-9133-4d22-a073-85a69cde57dd/jobs/5849) which is the version you mention.

If you understand more about exactly what the problem is, it would be great if you can save me some time and tell me what's actually broken and ideally what I need to change!

**Comment by floehopper** [comment]
And do you know if there was a Minitest deprecation warning for this? If so, I missed it!

**Comment by manewitz** [comment]
here's a backtrace if that's helpful:

```
/Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/mocha-2.0.4/lib/mocha/integration/mini_test/adapter.rb:26:in `included': uninitialized constant MiniTest (NameError)

          Mocha::ExpectationErrorFactory.exception_class = ::MiniTest::Assertion
                                                                     ^^^^^^^^^^^
Did you mean?  Minitest
	from /Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/mocha-2.0.4/lib/mocha/integration/mini_test.rb:21:in `include'
	from /Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/mocha-2.0.4/lib/mocha/integration/mini_test.rb:21:in `activate'
	from /Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/mocha-2.0.4/lib/mocha/minitest.rb:4:in `<main>'
	from <internal:/Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.9/lib/zeitwerk/kernel.rb:38:in `require'
	from /Users/mikemanewitz/work/coupons/test/test_helper.rb:10:in `<main>'
	from <internal:/Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.9/lib/zeitwerk/kernel.rb:38:in `require'
	from /Users/mikemanewitz/work/coupons/test/controllers/bulk_uploads_controller_test.rb:3:in `<main>'
	from <internal:/Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.9/lib/zeitwerk/kernel.rb:38:in `require'
	from /Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.6/lib/rails/test_unit/runner.rb:47:in `block in load_tests'
	from /Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.6/lib/rails/test_unit/runner.rb:47:in `each'
	from /Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.6/lib/rails/test_unit/runner.rb:47:in `load_tests'
	from /Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.6/lib/rails/test_unit/runner.rb:40:in `run'
	from /Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.6/lib/rails/commands/test/test_command.rb:33:in `perform'
	from /Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
	from /Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/honeybadger-5.2.1/lib/honeybadger/plugins/thor.rb:17:in `invoke_command_with_honeybadger'
	from /Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
	from /Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.6/lib/rails/command/base.rb:87:in `perform'
	from /Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.6/lib/rails/command.rb:48:in `invoke'
	from /Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.6/lib/rails/commands.rb:18:in `<main>'
	from <internal:/Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.9/lib/zeitwerk/kernel.rb:38:in `require'
	from /Users/mikemanewitz/work/coupons/bin/rails:5:in `<main>'
	from <internal:/Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from -e:1:in `<main>'
```

**Comment by kyrofa** [comment]
> And do you know if there was a Minitest deprecation warning for this? If so, I missed it!

You and I both :stuck_out_tongue: . Not that I know of, no. I logged an issue asking for confirmation that minitest actually uses semver, because I've been operating under the assumption that it does. Hopefully this was just an oversight, but it's a good reminder that we're using pretty old API, here.

> just manually ran [the weekly build](https://app.circleci.com/pipelines/github/freerange/mocha/415/workflows/121f5ace-9133-4d22-a073-85a69cde57dd) which tries to pick up on incompatibilities like this, but nothing failed [...].

I'll see if I can work up a minimal reproducer for you.

**Comment by manewitz** [comment]
When I edited the gem locally to use the `Minitest` casing it fixed my test suite. Might roll back to the last minitest for now.

**Comment by kyrofa** [comment]
Yeah I just pinned minitest to < 5.19 for now.

**Comment by kyrofa** [comment]
@floehopper run this:

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "minitest", "~> 5.19"
  gem "mocha", '~> 2.0'
end

require "minitest/autorun"
require 'mocha/minitest'
```

I see this:

```
$ $ ruby reproducer.rb 
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Using bundler 2.4.12
Using minitest 5.19.0
Using ruby2_keywords 0.0.5
Fetching mocha 2.0.4
Installing mocha 2.0.4
Traceback (most recent call last):
	5: from reproducer.rb:11:in `<main>'
	4: from reproducer.rb:11:in `require'
	3: from /home/kyrofa/.rvm/gems/ruby-2.7.5/gems/mocha-2.0.4/lib/mocha/minitest.rb:4:in `<top (required)>'
	2: from /home/kyrofa/.rvm/gems/ruby-2.7.5/gems/mocha-2.0.4/lib/mocha/integration/mini_test.rb:21:in `activate'
	1: from /home/kyrofa/.rvm/gems/ruby-2.7.5/gems/mocha-2.0.4/lib/mocha/integration/mini_test.rb:21:in `include'
/home/kyrofa/.rvm/gems/ruby-2.7.5/gems/mocha-2.0.4/lib/mocha/integration/mini_test/adapter.rb:26:in `included': uninitialized constant MiniTest (NameError)
Did you mean?  Minitest
```

**Comment by floehopper** [comment]
@manewitz:

Thanks for the backtrace - it certainly gives me a bit more to go on!

> When I edited the gem locally to use the `Minitest` casing it fixed my test suite. Might roll back to the last minitest for now.

Did you rename all occurrences of `MiniTest` -> `Minitest` throughout the Mocha codebase to fix it? That seems a bit challenging if we need to do that, because it will mean Mocha is no longer compatible with older versions of Minitest!

**Comment by floehopper** [comment]
@kyrofa Many thanks for the code to reproduce the problem 👍

**Comment by kyrofa** [comment]
> That seems a bit challenging if we need to do that, because it will mean Mocha is no longer compatible with older versions of Minitest!

It's worth a look at minitest. I'd be willing to bet the `Minitest` module has been "the way" for a very long time. The versions of minitest that only have `MiniTest` are probably extremely old.

**Comment by manewitz** [comment]
> @manewitz:
> 
> Thanks for the backtrace - it certainly gives me a bit more to go on!
> 
> > When I edited the gem locally to use the `Minitest` casing it fixed my test suite. Might roll back to the last minitest for now.
> 
> Did you rename all occurrences of `MiniTest` -> `Minitest` throughout the Mocha codebase to fix it? That seems a bit challenging if we need to do that, because it will mean Mocha is no longer compatible with older versions of Minitest!

I just updated the one call in `lib/mocha/integration/mini_test/adapter.rb:26` and it worked for me

**Comment by floehopper** [comment]
@manewitz 

> I just updated the one call in `lib/mocha/integration/mini_test/adapter.rb:26` and it worked for me

Yes, that seems to do the trick for me too (I've opened #615 to demo that), although I think there might be a bunch of other stuff to check and definitely some code to clean up. If anyone has a project with a lot of tests that using Mocha, it would be great if you could point your `Gemfile` at the `fix-minitest-compatibility` branch and see if you run into any other problems, i.e.

```ruby
# Gemfile

gem "mocha", github: "freerange/mocha", branch: "fix-minitest-compatibility"
```

**Comment by manewitz** [comment]
Looks like a 10 year old casing change: https://github.com/minitest/minitest/blob/master/History.rdoc#505--2013-06-20-

**Comment by zenspider** [comment]
1. Yes, the name change is **_over a decade old_**.
2. All that has changed is not requiring the cruft file.
3. You can `require "minitest/unit"` to avoid changing all instances of MiniTest to Minitest (but... c'mon... a decade).

**Comment by floehopper** [comment]
Fix released in [v2.1.0](https://rubygems.org/gems/mocha/versions/2.1.0). Thanks for your help, @kyrofa, @manewitz & @zenspider.

**Comment by kyrofa** [comment]
Thanks @floehopper, really appreciate it!

**Comment by Alex-Palad** [comment]
mocha is not compatible with minitest 5.19+
https://github.com/freerange/mocha/issues/614
