### ISSUE TITLE
Testing the block argument

### ISSUE THREAD

**Issue by vlad-pisanov** [freerange/mocha#685]
I'm trying to test a piece of code like this:
```ruby
Logger.log(:warning) { 'Some warning' }
```

The closest I've come up with so far is:
```ruby
Logger.expects(:log).with(:warning).with_block_given
```

What I'd like to do is something like:
```ruby
Logger.expects(:log).with(:warning).with_block_given do |block|
  block.call == 'Some warning'
end
```

Is there a way to do something like this in mocha? The [block_matcher only checks for block presence](https://github.com/freerange/mocha/blob/862237debd0787b6e5bb8df9e3ee5bdd14ef496c/lib/mocha/expectation.rb#L647) not its value.

**Comment by floehopper** [comment]
@vlad-pisanov Thanks for opening this issue. There isn't currently a way to do this with Mocha. Also the discussion in #493 includes the feature that you are suggesting here, so I'm going to add a comment to that issue referencing this one and then I'm going to close this as a duplicate.
